/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ec.edu.espol.workshops;


import ec.edu.espol.workshops.CarInsurance;



import static org.junit.jupiter.api.Assertions.*;



class LibraryTest {
    public static void main(String [] args) {
        System.out.println("Start");
        CarInsurance test = new CarInsurance();
        test.setAge(34);
        test.setSex('F');
        test.setMarried(true);
        System.out.println(test.getBasePremium());
    }
}